### ISSUE TITLE
Kevin G3AAF, link incorrect in roundtable-2019-program

### ISSUE THREAD

**Issue by DavidLutton** [CardiffARS/website#2]
http://www.rfdesign.co.uk/ is a redirect to something else

His site http://g8fek.com/index.html refers to going this event
http://rfdesignuk.com/index.html may have been the intended link 
Check with Kevin G3AAF

**Comment by dkozel** [comment]
Thanks @DavidLutton! I will check with Kevin and take down that link for the time being.

**Comment by dkozel** [comment]
Fixed in f61c039ad21992d7bbfa22d6e37668b4bbc329fa
